app:
  name: kafka
  description: A simple Kafka cluster
  image: bitnami/kafka
  ports:
    - 9092:9092
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  volumes:
    - name: data
      size: 1Gi
  environment:
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://localhost:9092
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: PLAINTEXT:PLAINTEXT
  depends_on:
    - zookeeper

zookeeper:
  image: bitnami/zookeeper
  ports:
    - 2181:2181
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
